chore(setup-test-coverage): setup test coverage
andela/rivendell-ah-client pull request #11
Opened 2018-09-06 09:26 UTC by chidioguejiofor

#### What does this PR do?
- installs jest and enzyme
- added jest.config to the app
- updates CircleCI config to run tests
- adds project to Code-climate
- ensures that build is passing on Circleci
- separates script for test and coverage
- adds repo token environmental variable to CircleCI
-adds badges to the README

#### Description of Task to be completed?
- acquire test coverage badge from code-climate
- configure test environment
- configure CircleCI to run test

#### How should this be manually tested?
- run `git pull` from console
- run `npm run test` to see test result
- run `npm run coverage` to see coverage results
- go to circleCi to view  branch build via https://circleci.com/gh/andela/rivendell-ah-client/127

#### Any background context you want to provide?
- None

#### What are the relevant pivotal tracker stories?
- 160056368 
- 160056367 
- 160056371

#### Screenshots (if appropriate)
<img width="1162" alt="screen shot 2018-09-06 at 1 23 49 am" src="https://user-images.githubusercontent.com/38565349/45148432-2b696f00-b1bf-11e8-8003-c937137ac99d.png">

#### Questions:
- None

2018-09-06 13:46 UTC, mppdg commented on .codeclimate.yml
> +
EOL

2018-09-06 13:46 UTC, mppdg commented on .eslintignore
> +tests/**/*.test.js
EOL

2018-09-06 13:48 UTC, mppdg commented on .codeclimate.yml
> +  - webppack.config.js
`webppack.config.js` wrongly spelt. Remove one of the Ps

2018-09-06 17:26 UTC, rhenshaw56 requested changes

2018-09-06 17:26 UTC, rhenshaw56 commented on jest.config.js
> +  coveragePathIgnorePatterns: [
add an option for a testUrl, so we don't have to come back for that

2018-09-06 17:26 UTC, rhenshaw56 commented on jest.config.js
> +    '\\.(css|scss)$': 'identity-obj-proxy',
you would also need to add for png, eof, woff types also

2018-09-06 17:26 UTC, rhenshaw56 commented on tests/config/setup.js
> +import Enzyme from 'enzyme';
change to enzyme

2018-09-07 11:05 UTC, JCanaks commented on .gitignore
>  <<<<<<< HEAD
remove conflict head

2018-09-07 11:06 UTC, JCanaks commented on .gitignore
>  <<<<<<< HEAD
resolve conflict

2018-09-07 11:34 UTC, JCanaks approved these changes

2018-09-07 12:13 UTC, mppdg approved these changes

2018-09-10 17:48 UTC, rhenshaw56 approved these changes

2018-09-10 17:48 UTC, merged