#160056365 setup basic react app
andela/rivendell-ah-client pull request #4
Opened 2018-08-29 15:49 UTC by tutugodfrey

#### What does this PR do?
Install dependencies and setup a react app

#### Description of Task to be completed?
- Install dependencies
- configure webpack for bundling
- add index.html
- create App component
 
#### How should this be manually tested?
- clone the repository and run `npm install` to install dependencies
- run `npm run dev` to serve the app

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#160056365

#### Screenshots (if appropriate)

2018-08-30 08:28 UTC, rhenshaw56 approved these changes
Please fix the hound comments

2018-08-30 08:28 UTC, rhenshaw56 commented on .babelrc
> +}
EOL

2018-08-31 15:35 UTC, rhenshaw56 commented on public/styles/App.scss
> +}
EOL

2018-09-04 11:04 UTC, rhenshaw56 requested changes
I stopped reviewing this PR when I saw the your build files here, can you tell me why it's here ?

2018-09-04 11:04 UTC, rhenshaw56 commented on .babelrc
> +		"env", "react"
what about the presets for stage-3 ?

2018-09-04 11:04 UTC, rhenshaw56 commented on .gitignore
> +.env
we won't be needing an env file so get rid of this

2018-09-04 11:04 UTC, rhenshaw56 commented on .hound.yml
> +  enabled: false
EOL

2018-09-04 11:28 UTC, rhenshaw56 requested changes

2018-09-04 11:28 UTC, rhenshaw56 commented on package.json
> +    "dotenv": "^6.0.0",
remove dotenv, you don't need it

2018-09-04 11:28 UTC, rhenshaw56 commented on public/styles/App.scss
> +	background-color: red;
can you use rgb() style instead of just inputing the colour names

2018-09-04 11:28 UTC, rhenshaw56 commented on webpack.config.js
> +          test: /.js$/,
add a test for .jsx also

2018-09-04 11:28 UTC, rhenshaw56 commented on webpack.config.js
> +const path = require('path');
add webpack config to eslintrc

2018-09-04 11:28 UTC, rhenshaw56 commented on src/index.js
> +import React from 'react';
@tutugodfrey @chidioguejiofor attend to this

2018-09-04 12:15 UTC, megame24 approved these changes

2018-09-04 12:55 UTC, rhenshaw56 approved these changes

2018-09-04 12:55 UTC, merged