#160283217 Update readme
andela/rivendell-ah-client pull request #9
Opened 2018-09-06 07:38 UTC by tutugodfrey

#### What does this PR do?
- Update readme

#### Description of Task to be completed?
- Add description of the application
- outline how the application can be started
- add the link to API Docs for building the application
- Add a table of the path/ routes available

#### How should this be manually tested?
- N/A

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
#160283217 

#### Screenshots (if appropriate)
-  N/A

#### Questions:
- N/A

2018-09-06 17:36 UTC, rhenshaw56 requested changes
The usual template for writing a readme usually has  the following headers.
FEATURES|GETTING STARTED|TECHNOLOGIES|CONTRIBUTIONS

I see none here

2018-09-06 17:36 UTC, rhenshaw56 commented on README.md
> +## Relevant urls
you don't need this api methods in here, take them off

2018-09-07 11:48 UTC, JCanaks commented on README.md
> +Authors Haven is am online application that bring together a community of authors and readers. It allows Authors to create and post articles based on topic of interest or popular demands. Reader can
correct typo  on  description it should be `Author's haven is 'an' online application that 'brings' together a community of authors .....It allows 'authors' (lowercase a)...... based on 'their' or popular 'demand' (singular). 'Readers' (plural)`

2018-09-07 11:49 UTC, JCanaks commented on README.md
> +- Users are able to mark articles as favorite
just simplify to  `users can mark an article a favorite`

2018-09-07 11:52 UTC, JCanaks commented on README.md
> +- Users are able to give ratings for articles
simplify to  `Users can rate an article`

2018-09-11 11:37 UTC, rhenshaw56 approved these changes

2018-09-11 15:44 UTC, JCanaks commented on README.md
> +Authors Haven is online application that brings together a community of authors and readers. It allows authors to create and post articles based on their topic of interest or popular demand. Readers
Author's have is 'an' online

2018-09-11 15:45 UTC, JCanaks commented on README.md
> +- Users Can mark articles as favorite
as 'a' favorite

2018-09-12 06:20 UTC, JCanaks approved these changes

2018-09-13 10:06 UTC, mppdg approved these changes

2018-09-14 11:27 UTC, merged